<?php
/**
 * Created by PhpStorm.
 * User: t0m
 * Date: 09/04/2018
 * Time: 14:30
 */

namespace AppBundle\Repository;

/**
 * KindDishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \Doctrine\ORM\EntityRepository
{
}