<?php

namespace AppBundle\Repository;

/**
 * KindDishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KindDishRepository extends \Doctrine\ORM\EntityRepository
{
}
