# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            entity: { class: AppBundle\Entity\User, property: username }

    encoders:
        AppBundle\Entity\User:
            algorithm: plaintext


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:   ^/login$
            anonymous: ~

        main:

            #security: false
            # this firewall applies to all URLs
            pattern: ^/

            # but the firewall does not require login on every page
            # denying access is done in access_control or in your controllers
            anonymous: true

            # This allows the user to login by submitting a username and password
            # Reference: https://symfony.com/doc/current/security/form_login_setup.html
            form_login:

                # The name of the route where the login form lives
                # When the user tries to access a protected page, they are redirected here
                login_path: security_login
                check_path: login_check
                success_handler: success.handler
                # Secure the login form against CSRF
                # Reference: https://symfony.com/doc/current/security/csrf_in_login_form.html
                csrf_token_generator: security.csrf.token_manager
                # The page users are redirect to when there is no previous page stored in the
                # session (for example when the users access directly to the login page).
                default_target_path: recipe_index


            logout:
                # The route name the user can go to in order to logout
                path: logout
                # The name of the route to redirect to after logging out
                target: home
    role_hierarchy:
        ROLE_ADMIN: ROLE_WRITER
    access_control:
        # require ROLE_ADMIN for /admin*
        #- { path: ^/admin/account, roles: ['ROLE_ADMIN', 'ROLE_WRITER'] }
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
